### ISSUE TITLE
Practice PR: Add NLU training data to the 'Mood' folder

### ISSUE THREAD

**Issue by EmmaWightman** [RasaHQ/contributors#16]
We are looking for more training data that relates specifically to **mood.** https://github.com/RasaHQ/NLU-training-data/tree/master/mood

You will find further guidance on the NLU training data README.md : https://github.com/RasaHQ/NLU-training-data

Still unsure where to start? Check out our guide: https://forum.rasa.com/t/how-to-make-a-code-contribution-to-rasa/11291

**Comment by Hakai-Shin** [comment]
Hello, I would like to contribute towards this issue.

**Comment by umangnangal** [comment]
Hey, I would like to contribute on this issue.

**Comment by shorouq-z** [comment]
Hey, is this still open?

**Comment by koaning** [comment]
Anybody is free to contribute examples that are missing. This is a long lived issue.

**Comment by shorouq-z** [comment]
That's great, @koaning, but I think you guys could make that a bit more clear. The "about" column says this: 

> The issues on this board are managed by the Rasa team. If you want to work on a specific issue, comment on it and someone from the Rasa team will approve it to you and move the issue to the section 'Doing'.

which is why I commented.
