### ISSUE TITLE
Migrating an existing assistant to Rasa 1.0 and Rasa X

### ISSUE THREAD

**Issue by JustinaPetr** [RasaHQ/contributors#6]
Are you a Rasa user who built and deployed the Rasa assistant before the release of Rasa 1.0 and Rasa X? If you have migrated your existing assistant to Rasa 1.0 and Rasa X, write up the steps and your experience so far in a tutorial or blogpost.

**Comment by mohankumargx** [comment]
Hi Justina, Built a bot earlier to release of Rasa 1.0, below are the steps i have followed to migrate to rasa 1.0

1. Backup the project folder (If in case mess up you can look for it)
2. Uninstalled rasa-nlu and rasa-core
3. Install rasa 1 using "pip install rasa" command
4. Create new folder and then run "rasa init " command which creates all the necessary files required. 
5. If you have training data in markdown(.md) format skip next step
6. Convert the training data (If you were used json format for training data) into mark down format using "rasa data convert nlu --data input_data_file --out nlu.md -f file_format{md} " and keep nlu.md file into the data folder.
7. init command default creates config.yml for supervised_embeddings pipeline.. if you are using other change accordingly 
8. Change the content of domain.yml, stories.md, endpoints.yml and actions.py.
9. Run "rasa train"command
10. Run "rasa interactive --endpoints endpoints.yml" for interactive learning
11. Run "rasa run actions --port port_number(Optional)" to run action server
12. Run "rasa shell --endpoints endpoints.yml" for talking to the bot
13. You may run "rasa test" to evaluating models

**Comment by JustinaPetr** [comment]
Hi @mohankumargx. That's awesome! :) A few questions:

- What is your assistant about and was it running in production before migrating it to Rasa 1.0?
- Have you used Rasa X with it already?
- What was the reasoning behind running `rasa init` if you already had files like domain, config files ready from your existing bot?

**Comment by mohankumargx** [comment]
@JustinaPetr 

- Assistant is all about providing information to clients regarding ticket and CI information like status,ETA, note and many more. The bot still in development stage
- I haven't used rasa x. I tried once but the interactive learning was broken, so didn't had time to identify and use it.
- I attended rasa x launch event, there you mentioned "rasa init" command creates all necessary files and directories. So wanted to explore and to remove redundant files such as  train_online.py , dialogue.py, nlu_model.py. All i wanted to optimize the code.

**Comment by rgstephens** [comment]
I wrote an article on migration [here](http://gstephens.org/rasa/chatbot/2019/01/01/rasa-1-migration.html)

**Comment by JustinaPetr** [comment]
Hi @rgstephens. Awesome! Thank you so much for sharing and also, thanks for including so much useful feedback :) We will reference the blogpost in our newsletter.

**Comment by rgstephens** [comment]
I've written another post related to migration on my blog at [gstephens.org](http://gstephens.org) and I've also created a command line tool, [rasacli](https://www.npmjs.com/package/rasacli) which can be useful both for migrating to Rasa X and to do bulk operations against Rasa X from the command line.

**Comment by mohankumargx** [comment]
@rgstephens  really a awesome blog. Thank you

**Comment by koaning** [comment]
@JustinaPetr I think we can close this one now 😅 ?

**Comment by JustinaPetr** [comment]
Yes! Closing it now.
