### ISSUE TITLE
Rasa and open source powered voice assistant

### ISSUE THREAD

**Issue by JustinaPetr** [RasaHQ/contributors#7]

**Comment by Zenleaf** [comment]
Hi @JustinaPetr great to see there is work being done on this issue. Just interested in the details, does it involve the development of an offline ASR similar to Snips or is it integration with voice assistants like Google Assistant or Amazon Alexa?

**Comment by JustinaPetr** [comment]
Hi @Zenleaf. This one is about using offline ASR. We already experimented with Google Assistant and Alexa before, you can find some results on that in the blogpost here: https://blog.rasa.com/going-beyond-hey-google-building-a-rasa-powered-google-assistant/

**Comment by Zenleaf** [comment]
Awesome thanks @JustinaPetr, will check it out.
