### ISSUE TITLE
Deploying Rasa on Raspberry Pi

### ISSUE THREAD

**Issue by JustinaPetr** [RasaHQ/contributors#9]
Do you have a Raspberry Pi at home and would like to test if it's possible to deploy Rasa assistant on it? Give it a go and write up your experience in a tutorial.

**Comment by JulianGerhard21** [comment]
Hi @JustinaPetr ,

I have written a tech-tutorial for this [here](https://github.com/RasaHQ/rasa/issues/4603#issuecomment-544272695) and I think I can write a Tutorial that has a better user experience by combining it with my SmartBoard (Video). How to proceed here, if I want to assign myself to this?

Regards
Julian
